services:
  - type: web
    name: interactive-product-tour-backend
    env: node
    buildCommand: npm install
    startCommand: node start.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
